resources:
  - name: source
    type: git
    source:
      uri: https://github.com/yashwantchavhan/NodeFileExist.git
      branch: master
jobs:
- name: test
  plan:
  - get: source
    trigger: true
  - task: install
    file: source/install.yml
  
